In [ ]:
import pandas as pd
from scipy.io import arff

from _libs.paths import PATHS

In [16]:
data, meta = arff.loadarff(PATHS["KIDNEY_DISEASE"])

In [23]:
df = pd.DataFrame(data)
df = df.map(lambda x: x.decode('utf-8') if isinstance(x, bytes) else x)

In [24]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.020,1,0,?,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4,0,?,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2,3,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4,0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2,0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd

In [25]:
df.to_csv(PATHS["KIDNEY_DISEASE"].replace(".arff", ".csv"), index=False)